### ISSUE TITLE
Support webpack v4

### ISSUE THREAD

**Issue by yuheiy** [RyotaSugawara/license-banner-webpack-plugin#10]
Do you have plans to follow webpack v4?

**Comment by RyotaSugawara** [comment]
Yeah, I will follow webpack v4 soon.
Please wait for a while.

**Comment by RyotaSugawara** [comment]
Released [v2.0.0](https://github.com/RyotaSugawara/license-banner-webpack-plugin/releases/tag/v2.0.0).

Check [here](https://github.com/RyotaSugawara/license-banner-webpack-plugin/tree/v2.0.0#production-mode-at-webpack-v4), then update your webpack configuration.
