### ISSUE TITLE
Deprecation warning Chunk.modules

### ISSUE THREAD

**Issue by RinkAttendant6** [RyotaSugawara/license-banner-webpack-plugin#8]
It appears that this plugin causes this warning upon build with Webpack 3:

> DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

I looked at the source code briefly and it is probably coming from https://github.com/RyotaSugawara/license-banner-webpack-plugin/blob/master/index.js#L93, looks like `chunk.mapModules` might be the most appropriate solution?

**Comment by RyotaSugawara** [comment]
Thanks for issue of deprecation warning.
I will fix this deprecated feature ASAP.

Also we have another issue for license comment at current version of UglifyJSPlugin.
UglifyJSPlugin won’t remove license comments, but we wan’t to remove all license comment and create new license banner comment.

So I am planning to improve this later.

**Comment by RinkAttendant6** [comment]
> UglifyJSPlugin won’t remove license comments, but we wan’t to remove all license comment and create new license banner comment.

It can be configured to remove all comments, and IMHO it shouldn't be this plugin's responsibility to do that. I think the best option is to inform your users on [how to configure UglifyJS](https://github.com/mishoo/UglifyJS2/tree/harmony#output-options) if they want all comments removed.

**Comment by RyotaSugawara** [comment]
Fixed it.
Please update to v1.0.0.
